# Generated by Django 4.2 on 2023-07-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketfetch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
