# Generated by Django 4.2 on 2023-07-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketdata', '0002_matchrestapidata_slug'),
        ('cricketdetails', '0002_cricketmatchdetails_batsman_name_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketmatchdetails',
            name='match_rest_api_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='cricketdata.matchrestapidata'),
        ),
    ]
