# Generated by Django 4.2 on 2023-07-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketdata', '0002_matchrestapidata_slug'),
        ('cricketdetails', '0003_alter_cricketmatchdetails_match_rest_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketmatchdetails',
            name='match_rest_api_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='cricketdata.matchrestapidata'),
        ),
    ]
