# Generated by Django 4.2 on 2023-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapi', '0003_directrestapi_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='directrestapi',
            name='batsman_name_1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='batsman_name_2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='batting_head',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='bowler_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='bowling_head',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='last_30th_balls',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='directrestapi',
            name='reviews',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
