# Generated by Django 4.2 on 2023-07-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapi', '0005_alter_directrestapi_team_1_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directrestapi',
            name='batsman_name_1',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='batsman_name_2',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='batting_head',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='bowler_names',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='bowling_head',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='last_30th_balls',
        ),
        migrations.RemoveField(
            model_name='directrestapi',
            name='reviews',
        ),
    ]
