# Generated by Django 4.2 on 2023-08-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapi', '0006_remove_directrestapi_batsman_name_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directrestapi',
            options={'ordering': ['match_id']},
        ),
    ]
