# Generated by Django 4.2 on 2023-08-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapi', '0007_alter_directrestapi_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectRestApi',
        ),
    ]
